// ============================================================
// SERVER-ONLY DATA — never imported by any client component.
// This file is the "brain" of the Magical Stories generator.
// It is only ever read inside app/api/generate/route.js, which
// runs exclusively on the server. The browser never receives
// this file's contents — only the final generated text.
// ============================================================

// CHARACTERS — animal-type (Beatrix Potter) and human-type (Pixar 3D)
const animalCharacters = [
  { name: "a wolf in grandmother's floral shawl and reading glasses, looking suspiciously innocent", tale: "The Wolf's Disguise" },
  { name: "a wolf sitting at a spinning wheel, trying very hard to look like a grandmother", tale: "The Wolf's Disguise" },
  { name: "a wolf carrying a basket of flowers he definitely did not steal from a little girl", tale: "The Wolf's Bouquet" },
  { name: "a wolf in a nightgown and bonnet tucked into an enormous bed, pretending to sleep", tale: "The Wolf's Bed" },
  { name: "a wolf in a coachman's cloak driving a pumpkin carriage through snowy woods", tale: "The Wolf Coachman" },
  { name: "a very large wolf in a very small apron baking gingerbread and looking quite pleased", tale: "The Wolf's Kitchen" },
  { name: "a wolf in a velvet cape standing at a crossroads, pointing three directions at once", tale: "The Wolf's Map" },
  { name: "a wolf in spectacles and a tweed jacket, trying to look scholarly in a library", tale: "The Wolf Scholar" },
  { name: "a wolf with muddy paws standing guiltily outside a house of straw", tale: "Three Little Pigs" },
  { name: "a reformed wolf in a striped scarf carrying a peace offering of honey cakes", tale: "The Reformed Wolf" },

  { name: "a small green frog sitting in a moonlit swamp, a prince's arrow landed softly beside her", tale: "The Frog Princess" },
  { name: "a frog perched on a prince's open palm in a dark forest, both looking rather surprised", tale: "The Frog Princess" },
  { name: "a frog in a tiny crown weaving at a golden loom in a candlelit tower room at night", tale: "The Frog Princess" },
  { name: "a frog baking bread in a warm kitchen, a trail of tiny floury footprints on the floor", tale: "The Frog Princess" },
  { name: "a beautiful young woman stepping out of a frog's skin in a beam of moonlight", tale: "The Frog Princess" },
  { name: "a princess in a golden gown dancing at a royal ball, fireflies circling her like stars", tale: "The Frog Princess" },
  { name: "a young prince holding a frog skin that is already beginning to dissolve into ash", tale: "The Frog Princess" },
  { name: "a frog sitting regally on a lily pad, a royal seal in one tiny webbed hand", tale: "The Frog Princess" },
  { name: "a princess weaving a carpet of impossible beauty, swans and flowers appearing as she works", tale: "The Frog Princess" },
  { name: "a frog and a young prince walking side by side on a path to a distant palace at dusk", tale: "The Frog Princess" },

  { name: "a cat in magnificent boots and a plumed hat, looking extremely smug", tale: "Puss in Boots" },
  { name: "a cat in boots bowing with great theatrical flair before an amused king", tale: "Puss in Boots" },
  { name: "a cat in muddy boots dragging an enormous sack through a moonlit field", tale: "Puss in Boots" },
  { name: "a cat in a plumed hat whispering a secret plan into a rabbit's enormous ear", tale: "Puss in Boots" },
  { name: "a cat in boots perched on a high wall, surveying a kingdom with great satisfaction", tale: "Puss in Boots" },
  { name: "a cat in boots chasing a very alarmed mouse through a palace corridor", tale: "Puss in Boots" },
  { name: "a cat in boots napping in a patch of sunlight, boots still on, hat over his face", tale: "Puss in Boots" },
  { name: "a cat in a feathered hat presenting a pheasant to a bewildered nobleman", tale: "Puss in Boots" },
  { name: "a cat in boots shaking paws with an ogre who is much larger and much less clever", tale: "Puss in Boots" },
  { name: "a very small cat in very large boots with a very confident expression", tale: "Puss in Boots" },

  { name: "a sleepy bear in a striped nightcap sitting in a rocking chair by the fire", tale: "Goldilocks" },
  { name: "three bears in aprons discovering their porridge has been eaten, looking baffled", tale: "Goldilocks" },
  { name: "a little bear cub in dungarees with a very empty bowl and a very sad face", tale: "Goldilocks" },
  { name: "papa bear in a tweed jacket reading a newspaper, pretending everything is fine", tale: "Goldilocks" },
  { name: "a mother bear in a floral apron making fresh porridge with extra care", tale: "Goldilocks" },

  { name: "a hare in bright red racing shoes asleep under an oak at the finish line", tale: "Aesop" },
  { name: "a tortoise in a little waistcoat plodding cheerfully past the sleeping hare", tale: "Aesop" },
  { name: "a hare in a racing scarf confidently waving at spectators before the race", tale: "Aesop" },
  { name: "a tortoise with a tiny finish-line ribbon around his neck, looking very pleased indeed", tale: "Aesop" },

  { name: "a field mouse in a flower-print dress holding a lantern taller than herself", tale: "Thumbelina" },
  { name: "a mole in a velvet dressing gown reading by the light of a single candle underground", tale: "Thumbelina" },
  { name: "a field mouse in a cosy apron laying a tiny supper table in her underground home", tale: "Thumbelina" },
  { name: "a mole in spectacles guiding a tiny girl through a candlelit underground tunnel", tale: "Thumbelina" },

  { name: "an owl professor in a mortarboard and gown with chalk-dusted paws at a tiny blackboard", tale: "The Forest School" },
  { name: "a rabbit gentleman in a blue tailcoat checking a pocket watch with great alarm", tale: "Folklore" },
  { name: "a ginger cat holding a magic golden fish very carefully in both paws", tale: "Folklore" },

  { name: "a small hedgehog baker in a flour-dusted apron pulling a perfect loaf from a forest oven", tale: "The Hedgehog's Bakery" },
  { name: "a badger librarian in a wool cardigan stamping books with an extremely serious expression", tale: "The Library Under the Hill" },
  { name: "a squirrel in a red coat who keeps losing her acorns and blaming the wind", tale: "The Forgetful Squirrel" },
  { name: "a fox in a velvet waistcoat pretending to be a doctor, with a tiny black bag and zero qualifications", tale: "Doctor Fox" },
  { name: "a raccoon in a striped coat organising his collection of shiny things by moonlight", tale: "The Collector" },
  { name: "a young wolf in a coachman's coat who is actually very shy and secretly writes poetry", tale: "The Gentle Wolf" },
  { name: "a weasel in a top hat selling magical umbrellas that open into other worlds", tale: "The Umbrella Shop" },
  { name: "a wise old hedgehog in spectacles giving advice nobody asked for but everyone secretly needs", tale: "Old Prickle's Wisdom" },
  { name: "a tiny mouse in a lace apron patiently teaching an enormous bear to make pastry", tale: "The Baking Lesson" },
  { name: "a silver fox who runs a tea shop at the very edge of the enchanted forest", tale: "The Forest Tea Room" },
  { name: "a badger and a rabbit sharing one small umbrella in the rain, looking very companionable", tale: "A Rainy Tuesday" },
  { name: "a chubby bear cub in dungarees trying to carry a jar of honey larger than his own head", tale: "The Honey Problem" },
  { name: "a dormouse in a nightcap fast asleep in a teacup, dreaming of cake", tale: "The Sleeping Dormouse" },
  { name: "a hedgehog in a little postman's bag delivering letters to mushroom houses", tale: "The Hedgehog Postman" },
  { name: "a fox cub in an oversized coat sitting by a fire eating soup from a very large spoon", tale: "The Fox Cub's Supper" },
  { name: "a dignified badger in a top hat conducting a tiny orchestra of forest mice", tale: "The Forest Concert" },
  { name: "a small raccoon in a chef's hat stirring something that smells wonderful and looks suspicious", tale: "The Midnight Kitchen" },
  { name: "a rabbit in a knitted jumper knitting another knitted jumper beside a warm fire", tale: "The Knitting Rabbit" },
];

const humanCharacters = [
  { name: "Little Red Riding Hood skipping along a forest path with a basket of warm bread", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood stopping to pick wildflowers, basket forgotten on the path", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood peering suspiciously at grandmother's ears, which seem unusually large", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood standing at a crossroads in a snowy forest, thinking carefully", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood sitting on a mossy log sharing sandwiches with a small fox", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood knocking on a cottage door, basket over her arm, quite unworried", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood reading a map of the forest upside-down with great confidence", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood in a snowy village street, red hood bright against white houses", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood sitting by a river, watching fish, entirely forgetting her errand", tale: "Little Red Riding Hood" },
  { name: "Little Red Riding Hood at a garden gate, offering a flower to a very surprised wolf", tale: "Little Red Riding Hood" },

  { name: "Cinderella in a tattered dress sweeping the hearth, a small mouse watching sympathetically", tale: "Cinderella" },
  { name: "Cinderella at midnight, one glass slipper on, one off, running down marble steps", tale: "Cinderella" },
  { name: "Cinderella in a moonlit garden, watching her carriage transform from a pumpkin", tale: "Cinderella" },
  { name: "Cinderella trying on her glass slipper with quiet disbelief and a very muddy foot", tale: "Cinderella" },
  { name: "Cinderella in rags talking to mice in a warm kitchen, all quite comfortable", tale: "Cinderella" },
  { name: "Cinderella asleep in a hay loft, surrounded by her small animal friends", tale: "Cinderella" },
  { name: "Cinderella in a silver gown at a grand ball, looking slightly overwhelmed but radiant", tale: "Cinderella" },
  { name: "Cinderella at a well in morning mist, drawing water, quietly dreaming", tale: "Cinderella" },
  { name: "Cinderella in a walled garden, tending roses, humming softly to herself", tale: "Cinderella" },
  { name: "Cinderella in a snowy courtyard, scattering crumbs for birds at dawn", tale: "Cinderella" },

  { name: "Rapunzel letting down her golden braid from a high tower window into the moonlit dark", tale: "Rapunzel" },
  { name: "Rapunzel at a tower window in morning light, braiding her hair with extraordinary patience", tale: "Rapunzel" },
  { name: "Rapunzel sitting in her tower room embroidering, surrounded by hanging plants and soft light", tale: "Rapunzel" },
  { name: "Rapunzel leaning out of a high tower window, watching a distant village with longing", tale: "Rapunzel" },
  { name: "Rapunzel in a sunny tower room reading an enormous stack of books, quite content", tale: "Rapunzel" },
  { name: "Rapunzel singing at her tower window, flowers climbing the stone walls below", tale: "Rapunzel" },
  { name: "Rapunzel on a green hillside for the first time, looking at everything with wide eyes", tale: "Rapunzel" },
  { name: "Rapunzel in a meadow with her hair loose, running barefoot for the very first time", tale: "Rapunzel" },
  { name: "Rapunzel at a market in a village, touching everything with wonder and delight", tale: "Rapunzel" },
  { name: "Rapunzel with a lantern at her tower window on a winter night, hair glowing like gold", tale: "Rapunzel" },

  { name: "Thumbelina sitting in a walnut shell boat on a puddle, looking very dignified", tale: "Thumbelina" },
  { name: "Thumbelina sleeping inside a tulip, curled up on a petal pillow", tale: "Thumbelina" },
  { name: "Thumbelina standing on a lily pad, watching dragonflies with delight", tale: "Thumbelina" },
  { name: "Thumbelina in a cosy underground room laid out by a field mouse, eating tiny soup", tale: "Thumbelina" },
  { name: "Thumbelina sitting on a windowsill in spring sunlight, smaller than a teacup", tale: "Thumbelina" },
  { name: "Thumbelina dancing on a flower petal in morning light, joyful and free", tale: "Thumbelina" },
  { name: "Thumbelina being carried in a pocket by a field mouse through a snowy landscape", tale: "Thumbelina" },
  { name: "Thumbelina in a walnut-shell bed under a rose-petal blanket, fast asleep", tale: "Thumbelina" },
  { name: "Thumbelina sitting in a daisy, waving to a bumblebee nearly the size of herself", tale: "Thumbelina" },
  { name: "Thumbelina on a leaf boat sailing a garden puddle, using a twig as an oar", tale: "Thumbelina" },

  { name: "the Snow Queen on her ice throne, looking magnificently cold and slightly bored", tale: "The Snow Queen" },
  { name: "the Snow Queen driving a white sleigh across a frozen lake in swirling snow", tale: "The Snow Queen" },
  { name: "the Snow Queen standing in a palace of ice at midnight, snowflakes her only company", tale: "The Snow Queen" },
  { name: "the Snow Queen at a tall ice window, watching the world below with cool curiosity", tale: "The Snow Queen" },
  { name: "Gerda trudging through a blizzard with a warm lantern and great determination", tale: "The Snow Queen" },
  { name: "Gerda in a garden of enchanted flowers that make her forget everything, smiling peacefully", tale: "The Snow Queen" },
  { name: "Gerda asking an old wise woman for directions in a snowy village", tale: "The Snow Queen" },
  { name: "Gerda at the gates of the Snow Queen's palace, small but completely unafraid", tale: "The Snow Queen" },
  { name: "Gerda and Kai walking home through spring meadows, the snow melting around them", tale: "The Snow Queen" },
  { name: "Gerda sheltering in a reindeer's warm coat in the far north, lantern beside her", tale: "The Snow Queen" },

  { name: "Sleeping Beauty asleep among rose thorns, perfectly peaceful, a small smile on her lips", tale: "Sleeping Beauty" },
  { name: "Sleeping Beauty in a rose-filled room where everyone and everything has fallen asleep", tale: "Sleeping Beauty" },
  { name: "Sleeping Beauty as a young girl in a castle garden, spinning a flower with no idea of her fate", tale: "Sleeping Beauty" },
  { name: "Sleeping Beauty at the moment of waking, sunlight just reaching her face through thorns", tale: "Sleeping Beauty" },
  { name: "Sleeping Beauty in a tower room at a spinning wheel, reaching out with one curious finger", tale: "Sleeping Beauty" },
  { name: "Sleeping Beauty walking in a castle where all the clocks stopped a hundred years ago", tale: "Sleeping Beauty" },

  { name: "the Little Mermaid sitting on sea rocks at sunset, watching ships on the horizon", tale: "The Little Mermaid" },
  { name: "the Little Mermaid at the bottom of the sea in a garden of coral and waving seagrass", tale: "The Little Mermaid" },
  { name: "the Little Mermaid holding a sunken ship's lantern in deep blue water", tale: "The Little Mermaid" },
  { name: "the Little Mermaid on the surface of the sea at night, watching stars and a sailing ship", tale: "The Little Mermaid" },
  { name: "the Little Mermaid taking her first steps on land, looking at her new feet with wonder", tale: "The Little Mermaid" },
  { name: "the Little Mermaid sitting on a moonlit beach, half in water, half on sand", tale: "The Little Mermaid" },
  { name: "the Little Mermaid beneath the sea watching a ship's shadow from below, hair floating", tale: "The Little Mermaid" },
  { name: "the Little Mermaid in a sea cave with a collection of human things, each one a mystery", tale: "The Little Mermaid" },

  { name: "Snow White in a forest clearing, lost, with seven curious small faces peering from the trees", tale: "Snow White" },
  { name: "Snow White sweeping a tiny cottage floor while seven pairs of boots are lined up at the door", tale: "Snow White" },
  { name: "Snow White asleep in a glass case in a forest, wildflowers growing all around her", tale: "Snow White" },
  { name: "Snow White at a cottage window, receiving an apple from a kind old woman, smiling", tale: "Snow White" },
  { name: "Snow White sitting at a tiny table laid for eight, wondering which seat is hers", tale: "Snow White" },
  { name: "Snow White in a winter forest, her dark hair against white snow, quite lost and unafraid", tale: "Snow White" },
  { name: "Snow White tending a kitchen garden, singing, while small animals bring her vegetables", tale: "Snow White" },
  { name: "Snow White in a forest at dusk, a deer beside her, fireflies rising around them", tale: "Snow White" },

  { name: "Gretel leaving a trail of breadcrumbs with one eye on the path and one on the sky", tale: "Hansel and Gretel" },
  { name: "Hansel and Gretel hand in hand at the edge of a very dark forest, sharing one lantern", tale: "Hansel and Gretel" },
  { name: "Gretel at a gingerbread cottage door, knocking politely despite everything", tale: "Hansel and Gretel" },
  { name: "Hansel in a cage made of gingerbread, looking cross but also eating part of the wall", tale: "Hansel and Gretel" },
  { name: "Gretel looking very determined in front of a very large oven", tale: "Hansel and Gretel" },
  { name: "Hansel and Gretel walking home through a brightening forest, pockets full of jewels", tale: "Hansel and Gretel" },

  { name: "Beauty curled up in an enormous enchanted armchair reading a very long book", tale: "Beauty and the Beast" },
  { name: "Beauty in an enchanted library where candles light themselves and books float to her hand", tale: "Beauty and the Beast" },
  { name: "Beauty at a long dinner table set for two, one chair enormous, one small, candles everywhere", tale: "Beauty and the Beast" },
  { name: "Beauty in a rose garden where every rose is perfect and every petal holds a secret", tale: "Beauty and the Beast" },
  { name: "Beauty at a tall castle window watching snow fall on an enchanted garden below", tale: "Beauty and the Beast" },
  { name: "Beauty holding a magic mirror that shows her family far away, tears on her cheeks", tale: "Beauty and the Beast" },

  { name: "the Little Match Girl lighting her last match in a snowy alley, face full of wonder", tale: "The Little Match Girl" },
  { name: "the Little Match Girl sitting in a doorway on New Year's Eve, matches in her small hands", tale: "The Little Match Girl" },
  { name: "the Little Match Girl warming her hands at a tiny flame, seeing a warm room in the light", tale: "The Little Match Girl" },
  { name: "the Little Match Girl asleep in the snow, surrounded by burned matches, peaceful", tale: "The Little Match Girl" },

  { name: "Assol as a little girl sitting on a cliff above the sea, watching sailing ships with bright eyes", tale: "The Scarlet Sails" },
  { name: "Assol on a beach at sunrise, one hand shading her eyes, watching the horizon", tale: "The Scarlet Sails" },
  { name: "Assol in a small wooden boat on a grey sea, scarlet fabric in her hands, dreaming", tale: "The Scarlet Sails" },
  { name: "Assol in a village at dusk, standing still while everyone moves around her, waiting", tale: "The Scarlet Sails" },
  { name: "Assol in a pine forest with the sea glittering below, a tiny scarlet sail in her pocket", tale: "The Scarlet Sails" },
  { name: "Assol wading in shallow sea water at dawn, holding her skirt, looking at the horizon", tale: "The Scarlet Sails" },

  { name: "a Leshy — the old forest spirit in a coat of bark and moss — leaning on a tree that leans back", tale: "Forest Folklore" },
  { name: "a Leshy sitting on a fallen log in deep forest, mushrooms growing from his hat, birds landing on him", tale: "Forest Folklore" },
  { name: "a tiny Domovoy — the house spirit — sitting by a warm hearth, knitting socks for the family cat", tale: "Home Folklore" },
  { name: "a small grumpy Domovoy in a nightcap, sweeping under the stove at midnight with a tiny broom", tale: "Home Folklore" },
  { name: "a Kikimora in a mossy dress, spinning thread in a swamp at moonrise, frogs watching politely", tale: "Swamp Folklore" },
  { name: "a Kikimora peering through a cottage window at night, looking more curious than frightening", tale: "Swamp Folklore" },

  { name: "a small boy in a green coat who collects lost buttons and posts them back to their owners", tale: "The Button Boy" },
  { name: "a girl with ink-stained fingers who writes spells in a notebook no one else can read", tale: "The Spell Writer" },
  { name: "a little girl who bakes moonlight into her bread so it glows softly at the dinner table", tale: "The Moonbread Baker" },
  { name: "a boy who accidentally turns things gold when he sneezes, looking very apologetic", tale: "The Golden Sneeze" },
  { name: "a young seamstress who sews pockets into clouds to store forgotten wishes", tale: "The Cloud Seamstress" },
  { name: "a cheerful girl with an enormous map of a kingdom that rearranges itself every Tuesday", tale: "The Map Girl" },
  { name: "a small solemn boy whose shadow is much braver than he is and goes on ahead", tale: "The Boy and His Shadow" },
  { name: "a young apprentice wizard who keeps turning his sandwiches into frogs by accident", tale: "The Sandwich Incident" },
  { name: "a girl in a yellow raincoat who collects raindrops in jars and sells them as different weathers", tale: "The Weather Seller" },
  { name: "a boy with unusually large ears who can hear exactly what flowers are whispering about", tale: "The Flower Listener" },
  { name: "a little witch in training whose spells always work perfectly — just never quite as intended", tale: "The Almost-Witch" },
  { name: "a fairy godmother in training who keeps conjuring the wrong-sized pumpkins", tale: "Godmother In Training" },
  { name: "a girl who keeps a jar of collected sunsets on her windowsill and opens them on grey days", tale: "The Sunset Keeper" },
  { name: "a small boy who is the official dream-watcher for his entire village and takes it very seriously", tale: "The Dream Watcher" },
  { name: "a girl who finds a door in the forest that opens into next Tuesday", tale: "The Tuesday Door" },
  { name: "a boy who can only be seen by cats, which he finds mostly convenient", tale: "The Cat Boy" },
  { name: "a girl who writes letters to the moon and finds them answered in morning frost on the window", tale: "Letters to the Moon" },
  { name: "a young miller's daughter who can spin straw into music, which is less useful but more beautiful", tale: "The Music Spinner" },
];

const locations = [
  "inside the hollow of an ancient oak tree lit by fireflies",
  "deep in a snowy forest where the trees whisper old stories to each other",
  "at a crossroads in the forest where three paths glow in three different colours",
  "in a sunlit clearing where mushrooms form a perfect fairy ring",
  "in a mossy dell where ferns grow tall and a brook sings quietly below",
  "in a forest glade where the trees grow so close the sky is just a green whisper above",
  "beside a woodland pond where moonlight lies on the water like spilled silver",
  "on a rocky shore where the sea crashes silver against dark stones at twilight",
  "on a sailing ship's bow above a glittering midnight sea",
  "beside a wide river at golden hour, willows trailing their fingers in the current",
  "on a wooden jetty above still water, mist rising from the surface at dawn",
  "at the edge of a frozen lake beneath the northern lights",
  "on a small island in the middle of a lake where swans sleep on dark water",
  "on a beach at low tide, sea glass and shells around bare feet",
  "in a sea cave where waves breathe in and out and the walls are encrusted with crystals",
  "on the steps of a gingerbread cottage with smoke curling from the chimney",
  "in the kitchen of a witch's cottage, shelves of strange jars catching the firelight",
  "beside a great stone fireplace where a kettle sings and a cat sleeps on the hearthrug",
  "in a cosy underground burrow with mossy walls, acorn lanterns, and a rag rug on the floor",
  "inside the hollow of a great tree fitted out as a home with a window and a door",
  "on a cottage porch at dusk, a rocking chair, a cup of tea, and fireflies rising",
  "in a baker's cottage garden where loaves cool on a windowsill in morning sun",
  "in the grand ballroom of a crumbling castle at midnight, one chandelier still lit",
  "in a tower room lined with dusty spellbooks and a round window overlooking mountains",
  "in a palace courtyard in winter, fountains frozen, snow on the golden domes",
  "on a castle drawbridge over a moat where golden fish drift slowly in dark water",
  "in a throne room where all the candles have blown out except one",
  "on castle battlements at dawn, mist in the valley below and a kingdom waking",
  "on a cobblestone village street in autumn, leaves swirling past coloured doorways",
  "at a lantern-lit market in an enchanted English village on a winter evening",
  "in a French village square where roses climb the walls and cats sleep on doorsteps",
  "along a country lane in bloom, hedgerows white with hawthorn blossom",
  "in a meadow in high summer, full of wildflowers and the sound of distant bells",
  "on a village green at dusk, smoke from chimneys, lamps being lit in windows",
  "on a hillside with a valley of a hundred rooftops and one lit window far below",
  "inside a glass mountain at sunset, every surface catching light like a prism",
  "on a floating island of clouds with a rope bridge swaying gently in the wind",
  "beneath the roots of a World Tree threaded with silver rivers and lanterns",
  "in a cave of crystals where time moves at its own unhurried pace",
  "at a tea table set in the middle of a rose hedge maze, teapot still warm",
  "beside a wishing well deep in ivy and forget-me-nots",
  "inside an enormous pumpkin coach rolling quietly through a moonlit lane",
  "in a secret garden where roses bloom in snow and the gate is always unlocked",
];

const magicObjects = [
  "a glowing lantern that shows the way to lost things",
  "a silver key that fits no visible lock",
  "a book whose pages rewrite themselves",
  "a hand mirror that shows the future",
  "a golden compass pointing toward home",
  "a velvet pouch spilling enchanted seeds",
  "a spinning spool of moonlight thread",
  "a music box playing a forgotten lullaby",
  "a glass slipper on a velvet cushion",
  "a basket of strange mushrooms that grant wishes",
  "an old map of a kingdom that no longer exists",
  "a small door no bigger than a teacup",
  "a jar of bottled starlight",
  "a feather that writes stories by itself",
  "an hourglass filled with golden sand that never runs out",
  "a wooden puppet with a conscience",
  "a cloak of invisibility stitched from shadows",
  "a wand carved from a lightning-struck oak",
  "a rose under a glass bell slowly losing its petals",
  "a cauldron bubbling with silver mist",
  "a cursed apple on a silver tray",
  "a spindle dripping with enchanted sleep",
  "a sack of beans that shimmer in moonlight",
  "a tiny red riding hood folded on a mossy stone",
];

const moods = [
  "mysterious and whimsical",
  "tender and melancholic",
  "dreamlike and ethereal",
  "cozy and heartwarming",
  "dark and enchanting",
  "magical and wonder-filled",
  "nostalgic and bittersweet",
  "serene and luminous",
  "playful and mischievous",
  "haunting and beautiful",
  "quiet and contemplative",
  "warm and golden",
  "cold and silvery",
  "ancient and timeless",
];

const lightings = [
  "soft candlelight casting long warm shadows",
  "cool blue moonlight filtering through pine branches",
  "warm golden lantern glow at dusk",
  "pale winter light on fresh snow",
  "dappled sunlight through enchanted leaves",
  "firefly-lit twilight in deep forest",
  "dramatic storm light with silver breaks in the clouds",
  "rosy sunrise mist over a still lake",
  "violet and gold sunset behind silhouetted trees",
  "the blue hour between twilight and dark",
  "bioluminescent light from glowing forest mushrooms",
  "flickering hearth fire casting orange warmth",
  "cold starlight and faint northern aurora",
  "soft grey morning fog with diffused light",
  "warm afternoon sun through stained glass",
];

const phenomena = [
  "snowflakes drifting like small white moths",
  "cherry blossoms falling in slow spirals",
  "autumn leaves turning copper and gold",
  "frost patterns spreading across old glass",
  "fireflies rising from night-dark grass",
  "a single ray of sunlight through storm clouds",
  "mist curling between ancient tree trunks",
  "rain of rose petals from a cloudless sky",
  "ice crystals forming on a spider's web",
  "first snowdrops pushing through frozen earth",
  "a comet's tail reflected in still water",
  "storm winds tearing at lantern light",
  "will-o'-the-wisps floating over dark water",
  "morning dew caught like diamonds in webs",
  "falling stars crossing a velvet sky",
];

const visualDetails = [
  "richly detailed with intricate storybook textures",
  "soft painterly quality with visible brushwork",
  "warm and luminous with deep tonal range",
  "delicate linework and fine crosshatching details",
  "jewel-toned palette with dramatic contrast",
  "soft sfumato edges and glowing highlights",
  "hand-crafted illustrative charm and depth",
  "cinematic depth of field with bokeh background",
  "lush textural detail like antique book illustration",
  "velvety deep shadows and luminous focal points",
];

const emotionalNotes = [
  "a moment of quiet wonder",
  "the held breath before magic happens",
  "the warmth of an old story remembered",
  "the ache of a beautiful and impossible thing",
  "pure childlike delight and surprise",
  "longing and hope intertwined",
  "tender courage in a frightening moment",
  "the bittersweet edge of a dream ending",
  "mischief about to tip into adventure",
  "ancient sadness and patient wisdom",
  "the electric stillness before transformation",
  "soft grief and small mercies",
  "wild joy barely contained",
  "the solemnity of a secret kept",
];

module.exports = {
  animalCharacters,
  humanCharacters,
  locations,
  magicObjects,
  moods,
  lightings,
  phenomena,
  visualDetails,
  emotionalNotes,
};
